<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Authentication\Authentication.csproj" />
        <ProjectReference Include="..\Coverage\Coverage.csproj" />
        <ProjectReference Include="..\HealthCard\HealthCard.csproj" />
        <ProjectReference Include="..\HealthcareProvider\HealthcareProvider.csproj" />
        <ProjectReference Include="..\Language\Language.csproj" />
        <ProjectReference Include="..\Notification\Notification.csproj" />
        <ProjectReference Include="..\SystemLog\SystemLog.csproj" />
        <ProjectReference Include="..\User\User.csproj" />
    </ItemGroup>

</Project>
